apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-postgresql
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.secret.postgres.password | b64enc | quote }}
  postgres-password: {{ .Values.secret.postgres.postgresPassword | b64enc | quote }}
